# -*- coding: utf-8 -*-
"""Copy of Bitirme Projesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJEQyKCPybLcOnRFLi8M_IV9NcZ3HDvY
"""

#huggingface'den data set çekildi
import pandas as pd
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("navyakamath03/student_performance_train")

#dataset dataframe olarak yüklendi
df = ds["train"].to_pandas()
df.head(5000)

#kolonlardaki data tipleri incelendi.
df = ds["train"].to_pandas()
df.dtypes



#!mkdir navyakamath03
#df.to_csv("navyakamath03/student_performance_train.csv", index=True)
#BigQuery'ye aktarım için kütüphane yüklendi.
#from google.colab import auth
#auth.authenticate_user()
#BigQuery'ye aktarım yapılması için proje seçimi yapıldı.
#PROJECT_ID = "	project-193faa7c-f9be-4fea-b4d"
#!gcloud config set project $PROJECT_ID
#BigQuery'ye aktarım yapıldı.
#!gsutil cp navyakamath03/student_performance_train.csv gs://bitirme_projesi123/

#BigQuery'deki temizlenmiş data colaba aktarıldı.

from google.colab import auth
auth.authenticate_user()
!gsutil -m cp gs://bq_export_mert/en_son_hali_*.csv .
import glob
import pandas as pd

output = "en_son_hali_final.csv"
first = True

files = glob.glob("en_son_hali_*.csv")
print("Bulunan dosya:", len(files))

for f in files:
    for chunk in pd.read_csv(f, chunksize=500_000):
        chunk.to_csv(output, mode="a", header=first, index=False)
        first = False

print("Hazır:", output)

dff=pd.read_csv("en_son_hali_final.csv")
dff.head()

"""Başarı oranını etkileyen örüntülerin incelenmesi"""

print(f"Minimum GPA: {dff['GPA'].min()}")
print(f"Maximum GPA: {dff['GPA'].max()}")
print(f"Min Attandance_Rate: {dff['AttendanceRate'].min()}")
print(f"Max Attandance_Rate: {dff['AttendanceRate'].max()}")
print(f"Min StudyHours: {dff['StudyHours'].min()}")
print(f"Max StudyHours: {dff['StudyHours'].max()}")

import pandas as pd
import numpy as np

dff["attendance_class"] = np.where(
    dff["AttendanceRate"] >= 0.9, "High Attendance",
    np.where(dff["AttendanceRate"] >= 0.6, "Normal Attendance", "Low Attendance")
)
dff["Success_Rate"] = np.where(
    dff["GPA"] >= 3.0, "Successful",
    np.where(dff["GPA"] >= 2.0, "Regular", "Failed")
)
dff["Study_Rate"] = np.where(
    dff["StudyHours"] >= 2.0, "Hard Worker",
    np.where(dff["StudyHours"] >= 1.0, "Regular", "Lazy")
)

dff["Success_Rate"].value_counts(normalize=True)

features = [
    "attendance_class",
    "Study_Rate",
    "InternetAccess",
    "ParentSupport",
    "activity",
    "PartTimeJob",
    "has_gf_bf",
    "FreeTime",
    "sociability"
]

for col in features:
    print("\n", col)
    display(
        dff.groupby(col)["Success_Rate"]
          .value_counts(normalize=True)
          .unstack()
          .round(3)
    )

pattern_2 = (
    dff.groupby(["attendance_class", "Study_Rate"])["Success_Rate"]
      .value_counts(normalize=True)
      .unstack()
      .round(3)
      .reset_index()
)

pattern_2

"""25-75 denemesi"""

dff["Success_Rate_global"] = pd.qcut(
    dff["GPA"],
    q=[0, 0.25, 0.75, 1],
    labels=["Failed", "Regular", "Successfull"])

dff["Success_Rate_global"].value_counts(normalize=True)

dff.groupby("Success_Rate_global")["GPA"].agg(
    min_gpa="min",
    max_gpa="max",
    count="count")

dff.groupby(
    "Success_Rate_global",
    observed=False
).agg(

    median_study=("StudyHours", "median"),
    median_att=("AttendanceRate", "median"),

)

dff["attendance_class"] = np.where(
    dff["AttendanceRate"] >= 0.94, "High Attendance",
    np.where(dff["AttendanceRate"] >= 0.9, "Normal Attendance", "Low Attendance")
)
dff["Study_Rate"] = np.where(
    dff["StudyHours"] >= 1.17, "Hard Worker",
    np.where(dff["StudyHours"] >= 1.0, "Regular", "Lazy")
)

features = [
    "attendance_class",
    "Study_Rate",
    "InternetAccess",
    "ParentSupport",
    "activity",
    "PartTimeJob",
    "has_gf_bf",
    "FreeTime",
    "sociability"
]

for col in features:
    print("\n", col)
    display(
        dff.groupby(col)["Success_Rate_global"]
          .value_counts(normalize=True)
          .unstack()
          .round(3)
    )

"""**AttandanceRate’i etkileyen faktörlerin incelenmesi**"""

# AttendanceRate ile Sayısal Değişkenlerin Korelasyon Analizi
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sadece sayısal (float ve int) olan sütunları analiz için seçiyoruz
numeric_cols = dff.select_dtypes(include=['float64', 'int64'])

# AttendanceRate sütununun diğer değişkenlerle olan korelasyonunu hesaplıyoruz
attendance_corr = numeric_cols.corr()['AttendanceRate'].sort_values(ascending=False)

print("AttendanceRate ile En Çok İlişkili Faktörler (Korelasyon):")
print(attendance_corr)

# Görselleştirme: Korelasyon Isı Haritası (Heatmap)
plt.figure(figsize=(4, 10))
sns.heatmap(numeric_cols.corr()[['AttendanceRate']].sort_values(by='AttendanceRate', ascending=False),
            annot=True,
            cmap='RdYlGn', # Kırmızıdan Yeşile (Pozitif-Negatif ayrımı için)
            fmt=".2f")
plt.title('AttendanceRate ile Değişkenlerin İlişkisi')
plt.show()

# Kategorik Değişkenlerin AttendanceRate Üzerindeki Etkisini İnceleme
import matplotlib.pyplot as plt
import seaborn as sns

# Okul Türü (SchoolType) ve Bölge (Locale) Bazlı Katılım Ortalamaları
plt.figure(figsize=(14, 5))

# Sol Grafik: Okul Türü
plt.subplot(1, 2, 1)
sns.barplot(data=dff, x='SchoolType', y='AttendanceRate', palette='Blues_d')
plt.title('Okul Türüne Göre Katılım Oranı')
plt.ylim(0.8, 1.0) # Farkları daha net görmek için

# Sağ Grafik: Bölge (Locale)
plt.subplot(1, 2, 2)
sns.barplot(data=dff, x='Locale', y='AttendanceRate', palette='Greens_d')
plt.title('Yaşanılan Bölgeye Göre Katılım Oranı')
plt.ylim(0.8, 1.0)

plt.tight_layout()
plt.show()

# Sayısal Olarak Grupları Görme
print("--- Okul Türü Bazında Katılım ---")
print(dff.groupby('SchoolType')['AttendanceRate'].mean())

print("\n--- Bölge (Locale) Bazında Katılım ---")
print(dff.groupby('Locale')['AttendanceRate'].mean())

# Kişisel Faktörlerin AttendanceRate Üzerindeki Etkisi
import matplotlib.pyplot as plt
import seaborn as sns

# Kişisel faktörlerin listesi
lifestyle_factors = ['PartTimeJob', 'has_gf_bf', 'ParentSupport']

plt.figure(figsize=(18, 5))

for i, factor in enumerate(lifestyle_factors):
    plt.subplot(1, 3, i+1)
    sns.barplot(data=dff, x=factor, y='AttendanceRate', hue=factor, palette='Set2', legend=False)
    plt.title(f'{factor} vs Katılım Oranı')
    plt.ylim(0.8, 1.0)

plt.tight_layout()
plt.show()

# Sayısal ortalamaları kontrol edelim
for factor in lifestyle_factors:
    print(f"--- {factor} Bazında Katılım ---")
    print(dff.groupby(factor)['AttendanceRate'].mean())
    print("-" * 30)

# Risk Altındaki Öğrencilerin (%10 En Düşük Katılım) Analizi

# Eşik değerini belirliyoruz (En düşük %10'luk dilim)
threshold = dff['AttendanceRate'].quantile(0.10)
dff['At_Risk'] = dff['AttendanceRate'] <= threshold

print(f"Katılım Oranı Eşik Değeri (En Düşük %10): {threshold:.2f}")

# Riskli Grup ile Normal Grubu Kıyaslayalım
risk_profile = dff.groupby('At_Risk')[['GPA', 'StudyHours', 'TestScore_Math', 'SES_Quartile']].mean()

print("\n--- Riskli Grup vs. Diğerleri (Ortalama Farklar) ---")
print(risk_profile)

# Görselleştirme: Riskli Grupta Aile Geliri Dağılımı
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 5))
sns.countplot(data=dff[dff['At_Risk'] == True], x='SES_Quartile', palette='OrRd')
plt.title('Risk Altındaki Öğrencilerin (Düşük Katılım) Aile Gelir Dağılımı')
plt.xlabel('Aile Gelir Seviyesi (1: En Düşük, 4: En Yüksek)')
plt.ylabel('Öğrenci Sayısı')
plt.show()

# Sosyal Faktörlerin Riskli Gruptaki Etkisi
import matplotlib.pyplot as plt
import seaborn as sns

# Riskli ve Normal grupların sosyal hayatlarını kıyaslayalım
social_comparison = dff.groupby('At_Risk')[['FreeTime', 'sociability', 'activity']].mean()

print("--- Riskli Grup vs. Diğerleri (Sosyal Hayat Faktörleri) ---")
print(social_comparison)

# Görselleştirme: Boş Zaman ve Sosyalleşme Karşılaştırması
plt.figure(figsize=(12, 6))

# Boş Zaman Dağılımı
plt.subplot(1, 2, 1)
sns.boxplot(data=dff, x='At_Risk', y='FreeTime', hue='At_Risk', palette='cool', legend=False)
plt.title('Risk Durumuna Göre Boş Zaman (FreeTime)')

# Sosyalleşme Oranı
plt.subplot(1, 2, 2)
sns.boxplot(data=dff, x='At_Risk', y='sociability', hue='At_Risk', palette='summer', legend=False)
plt.title('Risk Durumuna Göre Sosyalleşme (Sociability)')

plt.tight_layout()
plt.show()

# Gruplara Göre Risk Altında Olma Olasılığı (%)

def risk_percentage(column_name):
    return dff.groupby(column_name)['At_Risk'].mean() * 100

# Analiz etmek istediğimiz orijinal sütun isimleri
factors_to_check = ['SES_Quartile', 'ParentSupport', 'InternetAccess', 'PartTimeJob']

print("--- Grupların Riskli Bölgeye (En Düşük %10 Katılım) Girme Olasılıkları (%) ---")
for factor in factors_to_check:
    print(f"\n{factor} Bazında Risk Oranı:")
    print(risk_percentage(factor))

# Görselleştirme: Aile Desteği ve Gelir Durumunun Risk Oranına Etkisi
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 5))

# Aile Desteği vs Risk Oranı
plt.subplot(1, 2, 1)
risk_data = dff.groupby('ParentSupport')['At_Risk'].mean().reset_index()
risk_data['At_Risk'] *= 100 # Yüzdeye çevir
sns.barplot(data=risk_data, x='ParentSupport', y='At_Risk', hue='ParentSupport', palette='Reds_r', legend=False)
plt.title('Aile Desteği Yoksa Risk % Kaç Artıyor?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

# Gelir Durumu (SES_Quartile) vs Risk Oranı
plt.subplot(1, 2, 2)
income_risk = dff.groupby('SES_Quartile')['At_Risk'].mean().reset_index()
income_risk['At_Risk'] *= 100
sns.barplot(data=income_risk, x='SES_Quartile', y='At_Risk', hue='SES_Quartile', palette='YlOrRd', legend=False)
plt.title('Gelir Seviyesine Göre Risk Oranı (%)')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

plt.tight_layout()
plt.show()

# Kesişimsel Risk Analizi
# Olumsuz faktörlerin birleştiği "Hassas Grupları" oluşturalım

# Senaryo 1: Düşük Gelir (SES=1) VE Aile Desteği Yok (0)
dff['LowSES_NoSupport'] = (dff['SES_Quartile'] == 1) & (dff['ParentSupport'] == 0)

# Senaryo 2: Düşük Gelir (SES=1) VE İnternet Yok (0)
dff['LowSES_NoInternet'] = (dff['SES_Quartile'] == 1) & (dff['InternetAccess'] == 0)

print("--- Hassas Grupların Risk Oranları (%) ---")

print("\nDüşük Gelir + Aile Desteği Yok Grubu:")
print(dff.groupby('LowSES_NoSupport')['At_Risk'].mean() * 100)

print("\nDüşük Gelir + İnternet Yok Grubu:")
print(dff.groupby('LowSES_NoInternet')['At_Risk'].mean() * 100)

# Görselleştirme: Kesişimsel Riskler
import matplotlib.pyplot as plt
import seaborn as sns

groups = ['LowSES_NoSupport', 'LowSES_NoInternet']
risk_values = [dff[dff[g] == True]['At_Risk'].mean() * 100 for g in groups]
normal_risk = dff['At_Risk'].mean() * 100

plt.figure(figsize=(10, 6))
sns.barplot(x=groups + ['Genel Ortalama'], y=risk_values + [normal_risk], palette='coolwarm')
plt.axhline(normal_risk, color='black', linestyle='--')
plt.title('Birden Fazla Olumsuz Faktör Birleştiğinde Risk Değişiyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')
plt.show()

# Çalışma Alışkanlıkları (StudyHours) ve Katılım Arasındaki İlişki

# 1. Çalışma saatlerini gruplara ayıralım (Örn: 0-1 saat, 1-2 saat, 2+ saat)
def study_group(hours):
    if hours < 1: return 'Düşük (0-1 sa)'
    elif hours < 2: return 'Orta (1-2 sa)'
    else: return 'Yüksek (2+ sa)'

dff['Study_Group'] = dff['StudyHours'].apply(study_group)

# 2. Çalışma gruplarına göre Risk Oranı (%) ve Ortalama Katılım
study_analysis = dff.groupby('Study_Group').agg({
    'AttendanceRate': 'mean',
    'At_Risk': 'mean'
}).reset_index()

study_analysis['At_Risk'] *= 100 # Yüzdeye çevir
print("--- Çalışma Saatlerine Göre Katılım ve Risk Analizi ---")
print(study_analysis)

# 3. Görselleştirme
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(data=study_analysis, x='Study_Group', y='At_Risk', hue='Study_Group', palette='plasma', legend=False)
plt.title('Çalışma Alışkanlığı Azaldıkça Devamsızlık Riski Artıyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')
plt.show()

# Sosyal Hayat Düzeylerinin (sociability ve FreeTime) Katılım Riskiyle İlişkisi

# 1. Sosyalleşme (sociability) düzeyini gruplara ayıralım (1-2: Düşük, 3: Orta, 4-5: Yüksek)
def social_level(val):
    if val <= 2: return 'Düşük (1-2)'
    elif val == 3: return 'Orta (3)'
    else: return 'Yüksek (4-5)'

dff['Social_Level'] = dff['sociability'].apply(social_level)
dff['FreeTime_Level'] = dff['FreeTime'].apply(social_level) # Aynı mantığı FreeTime için de kullanalım

# 2. Sosyal düzeylere göre Risk Oranı (%) analizi
social_risk = dff.groupby('Social_Level')['At_Risk'].mean() * 100
freetime_risk = dff.groupby('FreeTime_Level')['At_Risk'].mean() * 100

print("--- Sosyalleşme Düzeyine Göre Devamsızlık Riski (%) ---")
print(social_risk)
print("\n--- Boş Zaman Düzeyine Göre Devamsızlık Riski (%) ---")
print(freetime_risk)

# 3. Görselleştirme: Sosyal Hayat vs Risk
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.barplot(x=social_risk.index, y=social_risk.values, hue=social_risk.index, palette='coolwarm', legend=False)
plt.title('Dışarı Çıkma Sıklığı Risk Oranını Değiştiriyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

plt.subplot(1, 2, 2)
sns.barplot(x=freetime_risk.index, y=freetime_risk.values, hue=freetime_risk.index, palette='viridis', legend=False)
plt.title('Boş Vakit Miktarı Risk Oranını Değiştiriyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

plt.show()

# Ebeveyn Eğitim Seviyesi (ParentalEducation) ve Katılım Riski

# 1. Eğitim seviyelerine göre Risk Oranı (%) ve Ortalama Katılım
parent_edu_analysis = dff.groupby('ParentalEducation').agg({
    'AttendanceRate': 'mean',
    'At_Risk': 'mean'
}).sort_values(by='At_Risk', ascending=False).reset_index()

parent_edu_analysis['At_Risk'] *= 100

print("--- Ebeveyn Eğitim Seviyesine Göre Katılım Analizi ---")
print(parent_edu_analysis)

# 2. Görselleştirme
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(data=parent_edu_analysis, x='ParentalEducation', y='At_Risk', hue='ParentalEducation', palette='magma', legend=False)
plt.title('Ebeveyn Eğitim Seviyesi Devamsızlık Riskini Etkiliyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')
plt.xticks(rotation=45)
plt.show()

# Katılım Oranı (AttendanceRate) vs. Akademik Başarı

# 1. Katılım oranlarını mantıklı gruplara ayıralım
def attendance_bucket(rate):
    if rate < 0.85: return '1. Düşük (<%85)'
    elif rate < 0.95: return '2. Orta (%85-95)'
    else: return '3. Yüksek (>%95)'

dff['Attendance_Level'] = dff['AttendanceRate'].apply(attendance_bucket)

# 2. Katılım seviyelerine göre tüm başarı metriklerinin ortalamasını alalım
score_analysis = dff.groupby('Attendance_Level').agg({
    'GPA': 'mean',
    'TestScore_Math': 'mean',
    'TestScore_Reading': 'mean',
    'TestScore_Science': 'mean'
}).reset_index()

print("--- Katılım Seviyesine Göre Başarı Tablosu ---")
print(score_analysis)

# 3. Görselleştirme: Katılım Seviyesi vs Notlar
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
# Notları "melt" ederek tek bir grafikte gösterelim
melted_scores = score_analysis.melt(id_vars='Attendance_Level', var_name='Ders', value_name='Ortalama_Not')
sns.barplot(data=melted_scores, x='Attendance_Level', y='Ortalama_Not', hue='Ders', palette='muted')

plt.title('Okula Katılım Arttıkça Başarı Nasıl Değişiyor?', fontsize=15)
plt.ylabel('Ortalama Puan / Not')
plt.ylim(0, 100) # Skorlar 100 üzerinden olduğu için
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""Study_Rate'i etkileyen faktörlerin incelenmesi:

*“Öğrencilerin çalışma düzenini (Study_Rate) hangi faktörler etkiliyor ve bu durum başarıya nasıl yansıyor?”

-Study_Rate, öğrencinin öğrenmeye ayırdığı gerçek eforu temsil eder.

-Study_Rate'i etkileyecek faktörleri sıralarsak;
*Study_Rate vs Sociability
*Study_Rate vs FreeTime
*Study_Rate vs ParentSupport
*Study_Rate vs InternetAccess
*Study_Rate vs Attendance
*Study_Rate vs Grade olabilir. Şimdi bunların analizlerini inceleyelim.
"""

dff.groupby("Study_Rate")["sociability"].mean()

#Sosyal aktivitenin Study_Rate'e etkisi pek olmuyor.

dff.groupby("Study_Rate")["FreeTime"].mean()
#Fazla boş zaman düşük yapılandırılmış çalışmaya sebep olabiliyor.

dff.groupby("Study_Rate")["ParentSupport"].mean()
#Aile desteği yüksek öğrenciler daha düzenli çalışıyor.

dff.groupby("Study_Rate")["InternetAccess"].mean()
#İnternet erişimi öğrenme fırsatlarını artırıyor.

dff.groupby("Study_Rate")["AttendanceRate"].mean()
#Devamlılık, çalışma disiplininin öncül göstergelerinden birisidir.

dff.groupby("Study_Rate")["Grade"].mean()
#Üst sınıflarda çalışma yükü artıyor.